name: C Build

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:

 build:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v2
   
   - name: Install GCC
     run: sudo apt-get install -y gcc
     
   - name: Build
     run: gcc -Wall -Wextra -o find_files paste.txt
     
   - name: Run Tests
     run: |
       mkdir test_dir
       touch test_dir/file1.txt test_dir/file2.txt
       mkdir test_dir/subdir
       touch test_dir/subdir/file3.txt
       ./find_files -name "*.txt" -path test_dir
       ./find_files -type f -path test_dir
       ./find_files -type d -path test_dir
       rm -rf test_dir
